# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: 'odoo'

# The runtime the application uses.
type: 'python:3.11'

# The hooks executed at various points in the lifecycle of the application.
hooks:
    # Build hooks can modify the application files on disk but not access any services like databases.
    build: !include
      type: string
      path: build.sh

    deploy: !include
      type: string
      path: deploy.sh

web:
    upstream:
      socket_family: tcp
      protocol: http
    commands:
      start: !include
        type: string
        path: run.sh 

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: "db:postgresql"

# The size of the persistent disk of the application (in MB).
disk: 2500

mounts:
  "/odoo": "shared:files/odoo"
  "/.local": "shared:files/local"
